name: CI

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

jobs:
  test:
    name: Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install Swift
      uses: swift-actions/setup-swift@v2.1.0
    - name: Run tests
      run: swift test --enable-code-coverage -Xswiftc -warnings-as-errors
    - name: Generate test coverage report
      if: ${{ matrix.os == 'ubuntu-latest' }}
      uses: maxep/spm-lcov-action@0.3.1
      with:
        output-file: ./coverage/lcov.info
    - name: Enforce test coverage threshhold
      if: ${{ matrix.os == 'ubuntu-latest' }}
      uses: VeryGoodOpenSource/very_good_coverage@v3.0.0
      with:
        path: ./coverage/lcov.info
        min_coverage: 100
    - name: Save PR number
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: |
        mkdir -p ./pr
        echo ${{ github.event.number }} > ./pr/NR
    - name: Move Coverage Report
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: mv ./coverage/lcov.info ./pr/lcov.info
    - name: Upload Coverage Information for Comment
      if: ${{ matrix.os == 'ubuntu-latest' }}
      uses: actions/upload-artifact@v4
      with:
        name: pr
        path: pr/

  swiftlint:
    name: SwiftLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Swift
        uses: swift-actions/setup-swift@v2.1.0
      - name: Install SwiftLint
        run: |
          curl -L https://github.com/realm/SwiftLint/releases/download/0.50.0/swiftlint_linux.zip -o swiftlint.zip
          unzip swiftlint.zip -d swiftlint
          ./swiftlint/swiftlint --version
      - name: Run SwiftLint
        run: ./swiftlint/swiftlint --strict --reporter github-actions-logging
